"""initial migration

Revision ID: 520cd8fbe3df
Revises: 
Create Date: 2022-02-28 00:13:00.257025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520cd8fbe3df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Initial Stats',
    sa.Column('primary_key', sa.String(), nullable=False),
    sa.Column('weight_metric', sa.Numeric(), nullable=False),
    sa.Column('weight_imperial', sa.Numeric(), nullable=False),
    sa.Column('height_metric', sa.Numeric(), nullable=False),
    sa.Column('height_imperial', sa.Numeric(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_table('Target Stats',
    sa.Column('primary_key', sa.String(), nullable=False),
    sa.Column('weight_metric', sa.Numeric(), nullable=False),
    sa.Column('weight_imperial', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('primary_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Target Stats')
    op.drop_table('Initial Stats')
    # ### end Alembic commands ###
